---
title: "Research"
---

## Authored Books
* Stockemer, D., & Bordeleau, J.-N. (2025). *Conspiracy Theories and Their Believers: A Comparative Outlook*. [cite_start]Cambridge University Press[cite: 38, 39].
* Stockemer, D., & Bordeleau, J.-N. (2023). *Quantitative Methods for the Social Sciences: A Practical Introduction with R*. [cite_start]Springer Nature Switzerland AG[cite: 40].
* Stockemer, D., & Bordeleau, J.-N. *Alternative 1*. [Forthcoming].

## Selected Peer-Reviewed Journal Articles
* Bordeleau, J.-N., Kretschmer, K., Hill, L., & Praino, R. (2025). "On the Relationship Between Age and Intentional Invalid Voting in Compulsory Elections." [cite_start]*Journal of Elections, Public Opinion and Parties*[cite: 46, 47].
* Bordeleau, J.-N. (2025). "Pre-election voter information interventions led by electoral management bodies can improve voter confidence." [cite_start]*Policy Studies*[cite: 49].
* Stockemer, D., & Bordeleau, J.-N. (2025). "Does Country Setting Make a Difference? A Cross-National Study on the Relationship Between Political Ideology and Conspiracy Mentality." [cite_start]*Social Science Quarterly*[cite: 50].
* Bordeleau, J.-N., & Stockemer, D. (2024). "On The Relationship Between Age and Conspiracy Beliefs." [cite_start]*Political Psychology*[cite: 52].
* Bordeleau, J.-N., & Stockemer, D. (2024). "Understanding climate change conspiracy beliefs: A comparative outlook." [cite_start]*Harvard Kennedy School Misinformation Review*[cite: 53].

## Knowledge Translation
* Bordeleau, J.-N., Chowdhury, I., & Praino, R. "4 pivotal elections around the world that will pose a test to democracy in 2026." [cite_start]*The Conversation* (2025)[cite: 122, 123].
* Bordeleau, J.-N., Kretschmer, K., Hill, L., & Praino, R. "Why are young people more likely to cast informal votes? It's not because they're immature." [cite_start]*The Conversation* (2025)[cite: 124, 125].
---
